rules:
  # Option 5: incoming PRs from renovate-bot
  - author: "renovate-bot"

    # Title for PRs from renovate-bot MUST start with `fix(deps):` or `chore(deps)"`.
    title: "^(fix|chore)\\(deps\\):"
