#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

######################################################################
# DOCAI WH Project - GCP Project in which DocAI WH has been provisioned
######################################################################
export DOCAI_WH_PROJECT_ID=${DOCAI_WH_PROJECT_ID:-$PROJECT_ID}
export DOCAI_WH_PROJECT_NUMBER=$(gcloud projects describe  "${DOCAI_WH_PROJECT_ID}" --format='get(projectNumber)')
export SA_DOCAI_WH="service-${DOCAI_WH_PROJECT_NUMBER}@gcp-sa-cloud-cw.iam.gserviceaccount.com"
gcloud config set project $DOCAI_WH_PROJECT_ID
export DOCAI_OUTPUT_BUCKET="$DOCAI_WH_PROJECT_ID-docai-output"  # Bucket for the DocAI output
export PROJECT_ID=${PROJECT_ID:-$DOCAI_WH_PROJECT_ID}

# Service Account to execute script, created inside DOCAI WH Project
export SA_NAME=docai-utility-sa
export SA_EMAIL=${SA_NAME}@${DOCAI_WH_PROJECT_ID}.iam.gserviceaccount.com
export KEY_NAME=${DOCAI_WH_PROJECT_ID}_${SA_NAME}.json
export KEY_PATH=${DIR}/${KEY_NAME}
export CALLER_USER=${SA_EMAIL}
export GOOGLE_APPLICATION_CREDENTIALS=${KEY_PATH}

######################################################################
# DOCAI Project - GCP Project with DocAI Processor used for document parsing
######################################################################
export DOCAI_PROJECT_ID=${DOCAI_PROJECT_ID:-$PROJECT_ID}
export DOCAI_PROJECT_NUMBER=$(gcloud projects describe  "${DOCAI_PROJECT_ID}" --format='get(projectNumber)')
export SA_DOCAI="service-${DOCAI_PROJECT_NUMBER}@gcp-sa-prod-dai-core.iam.gserviceaccount.com"


######################################################################
# PROJECT with GCS Data to be Loaded
######################################################################
export DATA_PROJECT_ID=${DATA_PROJECT_ID:-$PROJECT_ID}             # Project ID of the GCP Project in which GCS bucket is located for data to be loaded into the DW.

export DEBUG=true #For STDOUT output of logging

# PYTHON PATH
#export PYTHONPATH="${DIR}/../common/src"

# Additional parameters
echo "PROJECT_ID=$PROJECT_ID"
echo "DOCAI_WH_PROJECT_ID=$DOCAI_WH_PROJECT_ID, DOCAI_WH_PROJECT_NUMBER=$DOCAI_WH_PROJECT_NUMBER"
echo "DOCAI_PROJECT_ID=$DOCAI_PROJECT_ID,  DOCAI_PROJECT_NUMBER=$DOCAI_PROJECT_NUMBER"
echo "DATA_PROJECT_ID=$DATA_PROJECT_ID"
echo "PROCESSOR_ID=$PROCESSOR_ID"
echo "CALLER_USER=$CALLER_USER"
echo "DOCAI_OUTPUT_BUCKET=$DOCAI_OUTPUT_BUCKET"